language: python

python:
  - "2.7"

notifications:
  email: false

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - python tests.py
  - flake8 pymesync.py
  - flake8 tests.py
